### ISSUE TITLE
Error loading SimpleBrowser dll

### ISSUE THREAD

**Issue by nthakkur-mw** [SimpleBrowserDotNet/SimpleBrowser.WebDriver#35]
Hey,  I am using Specflow with SimpleBrowser and have added SimpleBrowser and SimpleBroswer.Driver nuget packges to my project. However, when I try to instantiate a new driver as: 

> var driver = new SimpleBrowserDriver();

I get following exception
`
System.TypeLoadException : Could not load type 'SimpleBrowser.Browser' from assembly 'SimpleBrowser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SimpleBrowser.WebDriver.BrowserWrapper..ctor()
   at SimpleBrowser.WebDriver.SimpleBrowserDriver..ctor()
   at SimpleBrowser.Steps.GivenGivenILoginToGatewayAdmin() in d:\Study\SimpleBrowser\Steps.cs:line 34`

What am I missing here? I also have references to Selenium.WebDriver and Selenium.Support. Here is my packages.config:

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="NUnit" version="3.0.0" targetFramework="net45" />
  <package id="Selenium.Support" version="2.46.0" targetFramework="net452" />
  <package id="Selenium.WebDriver" version="2.46.0" targetFramework="net452" />
  <package id="SimpleBrowser" version="0.5.79.0" targetFramework="net452" />
  <package id="SimpleBrowser.WebDriver" version="0.5.37" targetFramework="net452" />
  <package id="SpecFlow" version="2.1.0" targetFramework="net45" />
  <package id="SpecFlow.NUnit" version="2.1.0" targetFramework="net45" />
  <package id="SpecRun.SpecFlow" version="1.5.2" targetFramework="net45" />
</packages>`

**Comment by Teun** [comment]
Sorry, I am on holiday right now. Will get back to your question in a few
weeks.
Teun

Op 31 okt. 2016 20:07 schreef "Namrata Rea" <notifications@github.com>:

**Comment by nthakkur-mw** [comment]
Np. Thanks for letting me know!

**Comment by Teun** [comment]
OK, I tried to reproduce your issue. Added both SimpleBrowser and SimpleBrowser.WebDriver through the Package Manager Console. Then instantiate as you do without a problem. We have the same versions of Selenium, SimpleBrowser.WebDriver and SimpleBrowser. I can only ask you to try and do the same thing again in a fresh project. Maybe without the SpecFlow references? But this too should work. I have used SimpleBrowser from SpecFlow myself.
